# Generated by Django 4.2.28 on 2026-09-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], default=0, verbose_name='Dia da semana')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('disciplina', models.CharField(max_length=80, verbose_name='Disciplina')),
                ('local', models.CharField(blank=True, max_length=80, verbose_name='Local')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Cronograma',
                'ordering': ['horario', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(default='E. E. Santa Olímpia', max_length=120, verbose_name='Escola')),
                ('turma', models.CharField(default='3º ano B — Ensino Médio', max_length=80, verbose_name='Turma')),
                ('periodo', models.CharField(default='Manhã · 07:00 às 12:20', max_length=80, verbose_name='Período')),
                ('tema_claro', models.BooleanField(default=False, verbose_name='Tema claro')),
            ],
            options={
                'verbose_name': 'Configuração da escola',
                'verbose_name_plural': 'Configuração da escola',
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('titulo', models.CharField(blank=True, max_length=120, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('letivo', models.BooleanField(default=True, verbose_name='Dia letivo')),
            ],
            options={
                'verbose_name': 'Evento do calendário',
                'verbose_name_plural': 'Calendário',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('materia', models.CharField(max_length=80, verbose_name='Matéria')),
                ('entrega', models.DateField(verbose_name='Entrega')),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Prioridade')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['concluida', 'entrega', '-id'],
            },
        ),
    ]
